// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nltazzrxistkwldauhfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sdGF6enJ4aXN0a3dsZGF1aGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NzIwNjUsImV4cCI6MjA2NDM0ODA2NX0.i7Ta6Cr0mMF609Eoi8oY3f96kcBJByypHlDbugXB6ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);